---
- name: install riak
  yum: name=riak-{{ riak.version }} state=present

- name: configure iptables
  template: src=iptables.j2 dest=/etc/sysconfig/iptables.riak owner=root group=root
  notify:
  - lokkit
  when: firewall is defined
