---
- name: download riak ee
  get_url: url=http://s3.amazonaws.com/private.downloads.basho.com/riak_ee/20b089/1.4.1/ubuntu/precise/riak-ee_1.4.1-1_amd64.deb dest=/tmp/riak-ee_1.4.1-1_amd64.deb

- name: install riak ee
  command: /usr/bin/dpkg -i /tmp/riak-ee_1.4.1-1_amd64.deb

- name: set the riak ulimit
  copy: src=etc_default_riak_ulimit dest=/etc/default/riak

- name: configure iptables
  template: src=iptables.j2 dest=/etc/ufw/applications.d/riak owner=root group=root mode=0644
  when: firewall is defined

- name: update fw
  ufw: enable=yes allow=riak
  when: firewall is defined
