---
- hosts: riak_cluster
  sudo: True
  roles:
  - bootstrap/common

- hosts: Ubuntu
  gather_facts: no
  sudo: True
  roles:
  - bootstrap/ubuntu
  - riak_ee/ubuntu
  - riak_ee/common

- hosts: CentOS:RedHat
  gather_facts: no
  sudo: True
  roles:
  - bootstrap/redhat
  - riak_ee/redhat
  - riak_ee/common


