---
- hosts: riak_cluster
  sudo: True
  roles:
  - bootstrap/common

- hosts: Ubuntu
  gather_facts: no
  sudo: True
  roles:
  - bootstrap/ubuntu
  - riak/ubuntu
  - riak/common

- hosts: CentOS:RedHat
  gather_facts: no
  sudo: True
  roles:
  - bootstrap/redhat
  - riak/redhat
  - riak/common


